### PR TITLE
Loading spinner

### PR DESCRIPTION
**Pull request by Arcandres**
Spinner added for processes view.

### CODE REVIEW

**Review by husseinhareb — COMMENTED** [review]
Thanks for your contributions; I really appreciate them. I noticed that you created another commit for the pnpm file in this request, which was already committed in a previous pull. Could you explain the reason for this? Also, could you clarify the purpose of adding the pnpm file? I'm more familiar with npm and would like to understand the difference.

**Comment by Arcandres** [comment]
> Thanks for your contributions; I really appreciate them. I noticed that you created another commit for the pnpm file in this request, which was already committed in a previous pull. Could you explain the reason for this? Also, could you clarify the purpose of adding the pnpm file? I'm more familiar with npm and would like to understand the difference.

It was created automatically from pnpm, pnpm it is the very same as npm but reuses existing packages in order to not download them again.

**Comment by husseinhareb** [comment]
Understandable. I look forward to your future contributions! Haha!

**Comment by Arcandres** [comment]
> Understandable. I look forward to your future contributions! Haha!

Hey thanks, I plan to do more PR, but I am very new to React so I have to practice more before and maybe your project can teach me many things, great work btw, amazing app!

**Pull request merged**
